/**
 * Static repository registry — evidence from ACTUAL_STATE_AUDIT.md files only.
 * UNKNOWN where not verified. Updated by governance docs pass 005.
 */
import type { RepositoryEntry } from "./types";

export const REGISTRY_VERSION = "005";
export const REGISTRY_UPDATED = "2026-07-05";
export const REGISTRY_EVIDENCE =
  "docs/audits/ACTUAL_STATE_AUDIT.md (factory); external audits on feature branches for code-factory and standards-for-factory";

export const REPOSITORY_REGISTRY: RepositoryEntry[] = [
  {
    id: "factory-standards",
    canonicalName: "factory-standards",
    alternateNames: ["standards-for-factory", "The Law"],
    githubRepo: "masterchiefvoidking-sketch/standards-for-factory",
    npmPackage: "factory-standards",
    role: "Certification law — schemas, validator, scoring, tenant kit",
    department: "Factory Services (not a department)",
    buildingId: null,
    maturity: "beta",
    auditScore: 83,
    health: "yellow",
    integrationStatus: "verified",
    owns: [
      "JSON schemas",
      "Constitution/protocols",
      "Package validator CLI",
      "imports/ certification archive",
      "Compatibility matrix",
    ],
    mustNotOwn: [
      "SDK implementation",
      "HQ UI",
      "Tenant product runtime",
    ],
    provides: [
      "Validation reports",
      "Pass/fail + 0–100 scores",
      "Tenant certification kit",
      "Governance documentation",
    ],
    consumes: ["Certification packages (manual drop into imports/)"],
    blockers: [
      "Stale examples/ zips",
      "No typecheck script",
      "No CI workflow",
      "Duplicate nested copy in code-factory",
    ],
    evidenceSource:
      "standards-for-factory ACTUAL_STATE_AUDIT @ cursor/factory-standards-init-eb83",
    confidence: "high",
  },
  {
    id: "factory-core",
    canonicalName: "factory-core",
    alternateNames: ["code-factory", "@factory/core", "The Machinery"],
    githubRepo: "masterchiefvoidking-sketch/code-factory",
    npmPackage: "@factory/core",
    role: "Shared SDK — types, validators, certification helpers",
    department: "Factory Services (not a department)",
    buildingId: "engine-room",
    maturity: "prototype",
    auditScore: 74,
    health: "yellow",
    integrationStatus: "documented",
    owns: [
      "Factory domain TypeScript types",
      "JSON validators",
      "Certification package CLI",
      "Self-certification package",
    ],
    mustNotOwn: [
      "Canonical standards law (long-term)",
      "Tenant UIs",
      "HQ spatial shell",
    ],
    provides: ["@factory/core library", "create:package", "validate:package"],
    consumes: ["Standards rules (mirrored in src/standards/constants.ts)"],
    blockers: [
      "Repo naming confusion",
      "Nested factory-standards duplicate",
      "Not npm-published",
      "Self-audit only",
      "main branch placeholder README",
    ],
    evidenceSource:
      "code-factory ACTUAL_STATE_AUDIT @ cursor/factory-standards-validate-core-9173",
    confidence: "high",
  },
  {
    id: "factory",
    canonicalName: "Factory",
    alternateNames: ["factory HQ", "Titan Campus", "The Mill"],
    githubRepo: "masterchiefvoidking-sketch/factory",
    npmPackage: "factory",
    role: "Digital headquarters — govern, route, visualize, coordinate",
    department: "Executive / Campus",
    buildingId: "tower",
    maturity: "prototype",
    auditScore: 52,
    health: "orange",
    integrationStatus: "unwired",
    owns: [
      "Spatial campus UI",
      "Ecosystem map & governance docs",
      "Repository registry",
      "Control tower views",
      "Cross-repo coordination visibility",
    ],
    mustNotOwn: [
      "Standards schemas",
      "SDK validators",
      "Tenant business logic",
      "Direct app-to-app glue",
      "Fake live integrations",
    ],
    provides: ["HQ experience", "Governance documentation", "Integration visibility"],
    consumes: [
      "UNKNOWN live SDK — not wired per audit",
      "UNKNOWN live standards imports — not wired per audit",
    ],
    blockers: [
      "No persistence",
      "No live tenant integration",
      "Dead OperationsCenterInterior",
      "Mock operational data in UI",
    ],
    evidenceSource:
      "factory ACTUAL_STATE_AUDIT @ cursor/project-titan-building-architecture-1a9f",
    confidence: "high",
    notes: "Repair pass added typecheck/test scripts post-audit on cursor/repair-pass-1a9f",
  },
  {
    id: "bosslady",
    canonicalName: "BossLady",
    alternateNames: ["Boss Lady", "Chief Engineer"],
    githubRepo: null,
    npmPackage: null,
    role: "Engineering workshop — build, test, verify",
    department: "Department of Engineering",
    buildingId: "bosslady",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN — separate tenant repo not audited"],
    mustNotOwn: ["Factory governance", "Standards", "HQ shell"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN — intended @factory/core"],
    blockers: ["No repository audit", "Placeholder zip in standards imports only"],
    evidenceSource: "factory frozen tenant + standards imports placeholder",
    confidence: "low",
  },
  {
    id: "prime",
    canonicalName: "Forgina Prime",
    alternateNames: ["Prime", "Forgina", "Strategic Intelligence"],
    githubRepo: null,
    npmPackage: null,
    role: "Reasoning — think, plan, orchestrate",
    department: "Department of Reasoning",
    buildingId: "prime",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Factory governance", "Other tenant logic"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: ["No repository audit", "UI shell only inside factory"],
    evidenceSource: "factory frozen tenant registry",
    confidence: "low",
  },
  {
    id: "citadel",
    canonicalName: "Citadel",
    alternateNames: ["Chief Archivist", "Memory vault"],
    githubRepo: null,
    npmPackage: null,
    role: "Institutional memory — archive, history, records",
    department: "Department of Memory",
    buildingId: "citadel",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN — tenant repo not audited"],
    mustNotOwn: ["Factory object registry implementation", "Standards schemas"],
    provides: ["UNKNOWN — SDK has Citadel archive types only"],
    consumes: ["UNKNOWN — intended @factory/core"],
    blockers: [
      "No repository audit",
      "Placeholder zip in standards imports",
      "code-factory audit: next cert target",
    ],
    evidenceSource: "standards imports placeholder; code-factory Citadel SDK types",
    confidence: "low",
  },
  {
    id: "toolbelt",
    canonicalName: "Toolbelt",
    alternateNames: ["Horizon", "Knowledge library"],
    githubRepo: null,
    npmPackage: null,
    role: "Experience information — media, learning, collections",
    department: "Department of Knowledge",
    buildingId: "toolbelt",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "unknown",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Shared Factory search if centralized"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: [
      "Horizon referenced as invalid test fixture only (horizon-invalid)",
      "Toolbelt/Horizon relationship UNKNOWN",
    ],
    evidenceSource: "factory building + standards horizon-invalid fixture",
    confidence: "low",
    notes: "Prompt lists Horizon/Toolbelt — may be same or separate programs; UNKNOWN",
  },
  {
    id: "flippy",
    canonicalName: "Mr. Flippy",
    alternateNames: ["Flippy", "Web Flip Factory", "Release Captain"],
    githubRepo: null,
    npmPackage: null,
    role: "Shipping dock — package, release, distribute",
    department: "Department of Release",
    buildingId: "flippy",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN — release pipeline not audited"],
    mustNotOwn: ["Build logic (BossLady)", "Factory release law enforcement"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: [
      "Mr. Flippy canonical branch resolution — UNKNOWN",
      "Placeholder zip in standards imports",
    ],
    evidenceSource: "factory frozen tenant; repair queue item from prompt",
    confidence: "low",
  },
  {
    id: "forge",
    canonicalName: "Forge",
    alternateNames: ["The Forge", "Innovation Lab"],
    githubRepo: null,
    npmPackage: null,
    role: "Create — experiments, validation, venture proposals",
    department: "Department of Innovation",
    buildingId: "forge",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Engineering build", "Release shipping"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: ["No repository audit"],
    evidenceSource: "factory frozen tenant + building registry",
    confidence: "low",
  },
  {
    id: "fip",
    canonicalName: "FIP",
    alternateNames: ["Metrics Laboratory", "Quality"],
    githubRepo: null,
    npmPackage: null,
    role: "Measure — benchmarks, qualification, regression",
    department: "Department of Quality",
    buildingId: "fip",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Factory certification scoring (standards)"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: ["No repository audit"],
    evidenceSource: "factory frozen tenant + building registry",
    confidence: "low",
  },
  {
    id: "observatory",
    canonicalName: "Observatory",
    alternateNames: ["World Monitor", "Intake dome"],
    githubRepo: null,
    npmPackage: null,
    role: "Observe reality — signals, feeds, awareness",
    department: "Department of Intelligence",
    buildingId: "observatory",
    maturity: "scaffold",
    auditScore: null,
    health: "gray",
    integrationStatus: "placeholder",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Tenant-specific reasoning"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: ["No repository audit"],
    evidenceSource: "factory frozen tenant + building registry",
    confidence: "low",
  },
  {
    id: "sentinel",
    canonicalName: "Sentinel",
    alternateNames: ["Security Watcher"],
    githubRepo: null,
    npmPackage: null,
    role: "Threat monitoring — shares Observatory building",
    department: "Department of Intelligence",
    buildingId: "observatory",
    maturity: "idea",
    auditScore: null,
    health: "gray",
    integrationStatus: "unknown",
    owns: ["UNKNOWN"],
    mustNotOwn: ["Factory clearance UI (HQ owns campus security metaphor)"],
    provides: ["UNKNOWN"],
    consumes: ["UNKNOWN"],
    blockers: ["No dedicated building", "No repository audit"],
    evidenceSource: "factory nexus tenants.ts — frozen, buildingId observatory",
    confidence: "low",
  },
];

export function getRepository(id: string): RepositoryEntry | undefined {
  return REPOSITORY_REGISTRY.find((r) => r.id === id);
}

export function getRepositoriesByMaturity(
  level: RepositoryEntry["maturity"]
): RepositoryEntry[] {
  return REPOSITORY_REGISTRY.filter((r) => r.maturity === level);
}
