/**
 * Ecosystem status table — derived from audits + governance registry.
 * Not live CI data unless noted.
 */
import type { RepoStatusRow } from "./types";

export const FACTORY_STATUS_TABLE: RepoStatusRow[] = [
  {
    repo: "factory-standards",
    role: "The Law",
    department: "Factory Services",
    maturity: "beta",
    auditScore: 83,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "missing",
    docs: "good",
    factoryCertification: "N/A (is the certifier)",
    integrationStatus: "verified",
    blocker: "Stale zips/examples; no CI",
    nextRepair: "R-001",
    overall: "yellow",
  },
  {
    repo: "factory-core",
    role: "Shared SDK",
    department: "Factory Services",
    maturity: "prototype",
    auditScore: 74,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "pass",
    docs: "good",
    factoryCertification: "PASS 97/100 (standards imports)",
    integrationStatus: "documented",
    blocker: "Unpublished; monorepo confusion",
    nextRepair: "R-002",
    overall: "yellow",
  },
  {
    repo: "factory",
    role: "HQ / Control Tower",
    department: "Executive",
    maturity: "prototype",
    auditScore: 52,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "pass",
    docs: "partial",
    factoryCertification: "PASS 95/100 (standards imports)",
    integrationStatus: "unwired",
    blocker: "No live tenant wire; mock ops UI",
    nextRepair: "R-003",
    overall: "orange",
  },
  {
    repo: "bosslady",
    role: "Engineering tenant",
    department: "Engineering",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Placeholder zip only",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "R-006",
    overall: "gray",
  },
  {
    repo: "prime / forgina",
    role: "Reasoning tenant",
    department: "Reasoning",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "R-008",
    overall: "gray",
  },
  {
    repo: "citadel",
    role: "Memory tenant",
    department: "Memory",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Placeholder zip only",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "R-007",
    overall: "gray",
  },
  {
    repo: "toolbelt / horizon",
    role: "Knowledge tenant",
    department: "Knowledge",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "horizon-invalid fixture only",
    integrationStatus: "unknown",
    blocker: "Horizon/Toolbelt scope UNKNOWN",
    nextRepair: "R-009",
    overall: "gray",
  },
  {
    repo: "flippy",
    role: "Release tenant",
    department: "Release",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Placeholder zip only",
    integrationStatus: "placeholder",
    blocker: "Canonical branch UNKNOWN",
    nextRepair: "R-005",
    overall: "gray",
  },
  {
    repo: "forge",
    role: "Innovation tenant",
    department: "Innovation",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "fip",
    role: "Quality tenant",
    department: "Quality",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "observatory",
    role: "Intelligence tenant",
    department: "Intelligence",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "sentinel",
    role: "Security watcher",
    department: "Intelligence",
    maturity: "idea",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "unknown",
    blocker: "No repo; shares Observatory building",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
];

/** Factory HQ self-status (this repo, post repair-pass scripts) */
export const FACTORY_HQ_STATUS = FACTORY_STATUS_TABLE.find((r) => r.repo === "factory")!;
