/**
 * Ecosystem status table — derived from audits + governance registry + Proof #001.
 * Not live CI data unless noted.
 */
import { FIRST_CERTIFIED_TENANT_ID, PROOF_LOG } from "./proof-log";
import type { RepoStatusRow } from "./types";

export const FACTORY_STATUS_TABLE: RepoStatusRow[] = [
  {
    repo: "factory-standards",
    role: "The Law",
    department: "Factory Services",
    maturity: "beta",
    auditScore: 83,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "missing",
    docs: "good",
    factoryCertification: "N/A (is the certifier)",
    integrationStatus: "verified",
    blocker: "Stale zips/examples; no CI",
    nextRepair: "Maintain; re-validate tenants",
    overall: "yellow",
  },
  {
    repo: "factory-core",
    role: "Shared SDK",
    department: "Factory Services",
    maturity: "prototype",
    auditScore: 74,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "pass",
    docs: "good",
    factoryCertification: "PASS 97/100 (standards imports); completion pass succeeded",
    integrationStatus: "documented",
    blocker: "Unpublished; monorepo confusion",
    nextRepair: "Maintain core",
    overall: "yellow",
  },
  {
    repo: "factory",
    role: "HQ / Control Tower",
    department: "Executive",
    maturity: "prototype",
    auditScore: 52,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "pass",
    docs: "partial",
    factoryCertification: "PASS 95/100 (standards imports); self-cert proof pending (R-013)",
    integrationStatus: "unwired",
    blocker: "No live tenant wire; mock ops UI",
    nextRepair: "R-013",
    overall: "orange",
  },
  {
    repo: "bosslady",
    role: "Engineering tenant",
    department: "Engineering",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Not certified",
    integrationStatus: "placeholder",
    blocker: "No audit; not certified",
    nextRepair: "R-006",
    overall: "gray",
  },
  {
    repo: "prime / forgina",
    role: "Reasoning tenant",
    department: "Reasoning",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Not certified",
    integrationStatus: "placeholder",
    blocker: "No audit; not certified",
    nextRepair: "R-008",
    overall: "gray",
  },
  {
    repo: "citadel",
    role: "Local-first executive command center / institutional memory",
    department: "Memory",
    maturity: "beta",
    auditScore: null,
    build: "pass",
    tests: "pass",
    lint: "pass",
    typecheck: "pass",
    docs: "unknown",
    factoryCertification: "PASS 98/100 (Proof #001)",
    integrationStatus: "manual",
    blocker: "No live Factory integration; manual JSON import only; no CI on cert path",
    nextRepair: "R-011",
    overall: "yellow",
  },
  {
    repo: "toolbelt / horizon",
    role: "Knowledge tenant",
    department: "Knowledge",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "horizon-invalid fixture only; not certified",
    integrationStatus: "unknown",
    blocker: "Horizon/Toolbelt scope UNKNOWN; player/scope decision pending",
    nextRepair: "R-009",
    overall: "gray",
  },
  {
    repo: "flippy",
    role: "Release tenant",
    department: "Release",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "Not certified",
    integrationStatus: "placeholder",
    blocker: "Canonical branch UNKNOWN",
    nextRepair: "R-005",
    overall: "gray",
  },
  {
    repo: "forge",
    role: "Innovation tenant",
    department: "Innovation",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "fip",
    role: "Quality tenant",
    department: "Quality",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "observatory",
    role: "Intelligence tenant",
    department: "Intelligence",
    maturity: "scaffold",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "placeholder",
    blocker: "No audit",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
  {
    repo: "sentinel",
    role: "Security watcher",
    department: "Intelligence",
    maturity: "idea",
    auditScore: null,
    build: "unknown",
    tests: "unknown",
    lint: "unknown",
    typecheck: "unknown",
    docs: "unknown",
    factoryCertification: "None",
    integrationStatus: "unknown",
    blocker: "No repo; shares Observatory building",
    nextRepair: "UNKNOWN",
    overall: "gray",
  },
];

/** Factory HQ self-status (this repo, post repair-pass scripts) */
export const FACTORY_HQ_STATUS = FACTORY_STATUS_TABLE.find((r) => r.repo === "factory")!;

const citadelProof = PROOF_LOG.find((p) => p.id === "proof-001");

/** Proof summary for Control Tower static card */
export const PROOF_SUMMARY = citadelProof
  ? `Proof #001: ${citadelProof.repo} certified — ${citadelProof.certificationScore}/100 — manual integration only`
  : "No proofs recorded";

export const FIRST_CERTIFIED_TENANT = FIRST_CERTIFIED_TENANT_ID;
